dist: bionic
language: bash
cache:
- "$HOME/.ccache"
addons:
  apt:
    packages:
    - ccache
services:
- docker
before_install:
- docker pull m0rf30/arch-arm-crosscompile
script:
- docker run -u root -v $HOME/.ccache:/ccache -v $(pwd):/workspace m0rf30/arch-arm-crosscompile:latest
  bash -c "cd /workspace/; CCACHE_DIR=/ccache ./build.sh"
deploy:
  provider: releases
  api_key:
    secure: GuixfcF1S2Qti1OQ3Cuu0WivDcaLq57g9alblcwyGINdKPgI9unnRz+3EKfwR0shKTQuphIPLBCSawwR7wKnPJY3WqjBrQJCUKU0M3HcZyhrRnf52Ys+ly6gukrsxxplEm5DJeKjn+6+O4uG97Dkp/0RxgxfyJj1Hily4/YUA7xmVOmflnH6VrS4CWP8SMB3mQYWqTOCJWa8xAAGwog4XkUg0yE0o7A8LP0YjQsamqVHXDfB5xstffhNAL12WFWOQHjVXeLNJD4aDkvdDlMMsvLz4FJwBsLWwj3IoxC6jANb6YerThpCRllEeIZfpA7X+aW9Ia7Ggwubq4QuhqQ+IcjihFqkaL7gQm0egiOxlxT+1el5rtBCCCRuG/0k7nOdz/7oNRb/jPJVj6LgDZPd44UnPRLQ0rUwcr7ZZ1HMZkDRU3LkZnBua8gmyTW20n7kqPlNCHbpECgCJF6+Jy0E2MWacWFVPapDAlW+98I87BrNncKxMVDYEdvlJ9mfOXqm6ya/4E/rrnqx1XMpJ9/+GyZnuHjoQW6K1RzMCUOlzvoO6zI39SnBDG9D50Qf6qA3TsAr0I2Ed76KinACppEDuUtpNxGxS4O8D+gQzlPPM5DzgKXOVca9hm9xgd2e1eVLq2vZkQAtpmsqPjVH8yoZvhT6MtaslbSS1EfVgCYK24A=
  file_glob: true
  skip_cleanup: true
  file: build/*
  on:
    repo: M0Rf30/qemu-kernel-rpi2
    branch: rpi2
    tags: false
