dist: bionic
language: bash
cache:
- "$HOME/.ccache"
addons:
  apt:
    packages:
    - ccache
services:
- docker
before_install:
- docker pull m0rf30/arch-arm-crosscompile
script:
- docker run -u root -v $HOME/.ccache:/ccache -v $(pwd):/workspace m0rf30/arch-arm-crosscompile:latest
  bash -c "cd /workspace/; CCACHE_DIR=/ccache ./build.sh"
deploy:
  provider: releases
  api_key:
    secure: Zss3wWIX9QUJZeefJmEt583tmcVDMeR/d3F1ZnQ9tZXfZ9hrlly/vTlCu7UekXtcABYFEjGDff8YBMbp32FCqQNR8bx6qCDmVIoq1DuGIRHY4qgO46Lm4qjX/TDc1U3J0lfstk20/z1/+rRMPac2PGLqT1uaQ8JuWqJdpA2g8TICs6M2aipfH3EFLRZAw040xgOivS9bMj+wikFr2eLm0/3lIe4Dwc/Fq0oREfrVKQCHwtD/fp3UAVmAMLhy2IBaOuER6OnaMeNu9Zokm3XrYdMAeo4GbhWNubkaxDbZ/czxzQSdzSMj1ZrPA66/o2I4SwKky5ngSZ4gt6bhLJMsB9G+Ect858X0EVfwIT6042D2IDGSHnBS76RzYDXPwgu6dMy454RSKLSQhwyGNgjiOHywOuCSZ76DsdJ7kKwPUrp5MB/iORBxbnBqMVsd/7vHt+dvfA8QAmXLbvqCmriqWWLuSEVhrPA22yp9RjZ4WTxvzRTiIYBWjxqWQI82V5D2vqgDsLpoqo3Lyfmcyq9ME69GlMBmPF07iLKOFnKt5zLxkkLNnOewr3SVRAlM/X6iAPHT8euV3x+P7sQQaGAgSnVjho4jqLAXyciwNtYPzPRhlREnMJ+oVdtq6YndzL6BVVPkWQy6Cuz2UwK3tFwVqkwARL0C4x9jC4xeBOFxaTA=
  file_glob: true
  skip_cleanup: true
  file: build/*
  on:
    repo: M0Rf30/qemu-kernels-rpi-arch-arm
    branch: rpi2
    tags: false
